linter:
  rules:
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - always_declare_return_types
    - avoid_unnecessary_containers
    - avoid_positional_boolean_parameters
    - file_names
    - prefer_const_constructors

analyzer:
  errors:
    file_names: error